
NUM_CASILLAS_TABLERO = 68
NUM_CASILLAS_LLEGADA = 8
COLORES = ['Rojo', 'Azul', 'Verde', 'Amarillo']
FICHAS_POR_JUGADOR = 4
MAX_FICHAS_POR_CASILLA = 2
VALOR_SALIDA = 5
MOV_EXTRA_CAPTURA = 20
MOV_EXTRA_LLEGADA = 10
